language: java
jdk:
  - openjdk11

brances:
  only:
    - master

cache:
  directories:
    - '$HOME/ .2/repository'
    - '$HOME/ .gradle'

script: "./gradlew clean build"

notification:
  email:
    recipients:
      - wjdrbs966@naver.com

