language: java
jdk:
  - openjdk11

brances:
  only:
    - master

cache:
  directories:
    - '$HOME/ .2/repository'
    - '$HOME/ .gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r SpringBoot_CI-CD *
  - mkdir -p deploy
  - mv SpringBoot_CI-CD.zip deploy/SpringBoot_CI.CD.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: gyunny
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notification:
  email:
    recipients:
      - wjdrbs966@naver.com


